### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by CDRX2** [Petro31/ad_convert_media_volume#2]
Hi,

I was wondering if this is still working for you. It seems to have stopped working for me sometime in the last few weeks (hard to tell when exactly).

I get the following error in the Appdaemon logs (haven't had time to delve into debug logs yet):

```
2023-05-30 18:05:57.492790 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/ad_convert_media_volume/convert_media_volume.py
2023-05-30 18:05:57.503260 WARNING Error: ------------------------------------------------------------
2023-05-30 18:05:57.503693 WARNING Error: Unexpected error loading module: /config/appdaemon/apps/ad_convert_media_volume/convert_media_volume.py:
2023-05-30 18:05:57.504184 WARNING Error: ------------------------------------------------------------
2023-05-30 18:05:57.511467 WARNING Error: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 1000, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 783, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/appdaemon/apps/convert_media_volume/convert_media_volume.py", line 2, in <module>
    import voluptuous as vol
ModuleNotFoundError: No module named 'voluptuous'
2023-05-30 18:05:57.512057 WARNING Error: ------------------------------------------------------------
2023-05-30 18:05:57.512706 WARNING AppDaemon: Removing associated apps:
2023-05-30 18:05:57.513632 WARNING AppDaemon: salon_volume
2023-05-30 18:05:57.518540 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/convert_media_volume/convert_media_volume.py
2023-05-30 18:05:57.527711 INFO Error: Previous message repeated 1 times
2023-05-30 18:05:57.528464 WARNING Error: Unexpected error loading module: /config/appdaemon/apps/convert_media_volume/convert_media_volume.py:
2023-05-30 18:05:57.529022 WARNING Error: ------------------------------------------------------------
2023-05-30 18:05:57.532828 WARNING Error: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 1000, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 783, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/appdaemon/apps/convert_media_volume/convert_media_volume.py", line 2, in <module>
    import voluptuous as vol
ModuleNotFoundError: No module named 'voluptuous'
2023-05-30 18:05:57.533355 WARNING Error: ------------------------------------------------------------
2023-05-30 18:05:57.533965 WARNING AppDaemon: Removing associated apps:
```
Wondering if maybe there's something I should have done with a HA Update...

I'm running HAOS 10.2, Home Assistant 2023.5.4

If you have any pointers, I'd much appreciate it.

**Comment by Petro31** [comment]
seems like you need to install voluptuous in appdeamon.  I'm checking with the AD guys now, maybe something changed on their end.

**Comment by Petro31** [comment]
Just checked into it.  You need to add voluptuous as a dependency via the addon in HA's ui.

**Comment by CDRX2** [comment]
That was it, thank you very much!
